/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* dynports =  1  *)
(* cells_not_processed =  1  *)
(* src = "adder2bit.v:1" *)
module adder2bit(a_in, b_in, o_sum);
  (* src = "adder2bit.v:4" *)
  input [1:0] a_in;
  (* src = "adder2bit.v:5" *)
  input [1:0] b_in;
  (* src = "adder2bit.v:6" *)
  output [2:0] o_sum;
  (* src = "adder2bit.v:9" *)
  wire r_c0;
  (* src = "adder2bit.v:10" *)
  wire r_s1;
  assign o_sum[0] = a_in[0] ^(* src = "adder2bit.v:12" *)  b_in[0];
  assign r_c0 = a_in[0] &(* src = "adder2bit.v:13" *)  b_in[0];
  assign r_s1 = a_in[1] ^(* src = "adder2bit.v:15" *)  b_in[1];
  assign o_sum[1] = r_s1 ^(* src = "adder2bit.v:16" *)  r_c0;
  assign o_sum[2] = a_in[1] &(* src = "adder2bit.v:17" *)  b_in[1];
endmodule
